#!/bin/bash

# Get Mouse atlas data from Marioni
curl https://content.cruk.cam.ac.uk/jmlab/atlas_data.tar.gz > ./Analysis/Pijuan/rawData/atlas_data.tar.gz

mkdir Analysis/Pijuan/rawData
tar -xf ./Analysis/Pijuan/rawData/atlas_data.tar.gz atlas/genes.tsv atlas/barcodes.tsv atlas/meta.tab atlas/raw_counts.mtx -C ./Analysis/Pijuan/rawData
mv -f ./atlas/* ./Analysis/Pijuan/rawData
rm -r ./atlas